# <font color = aquamarine> Numpy
  <font color = azure>

<div style = "text-align : left"> NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. 
</div> 

<font color = aquamarine>

**Documentation**: 
 - **Numpy**: https://numpy.org/doc/stable/
 - **Python**: https://docs.python.org/3/library/index.html

### <font color = Azure> Importing Numpy

In [3]:
import numpy as np

### <font color = Azure> Arrays

##### <font color = antiquewhite> Building Arrays

In [4]:
# Using np.arange
array = np.arange(10)
print("arange:", array)

# Using np.array with a list
array = np.array([1, 2, 3, 4, 5])
print("np.array:", array)

# Using an external file
array = np.loadtxt('example_data.txt', delimiter=',', dtype = "int")
print("np.loadtxt:", array)

arange: [0 1 2 3 4 5 6 7 8 9]
np.array: [1 2 3 4 5]
np.loadtxt: [10 20 30 40 50]


##### <font color = antiquewhite> Two dimensional arrays

In [12]:
array = np.array([[1,3,5,7,9],[0,2,4,6,8]])
print("Two dimensional array (Matrix):")
print(array)

Two dimensional array (Matrix):
[[1 3 5 7 9]
 [0 2 4 6 8]]


##### <font color = antiquewhite> Attributes

In [7]:
print('Shape: ', array.shape, '\nDimensions: ', array.ndim, '\nSize: ', array.size, '\nData type: ', array.dtype) 	

Shape:  (2, 5) 
Dimensions:  2 
Size:  10 
Data type:  int32


##### <font color = antiquewhite> Methods

In [15]:
# Transpose
array.T

array([[1, 0],
       [3, 2],
       [5, 4],
       [7, 6],
       [9, 8]])

In [14]:
# To list
array.tolist()

[[1, 3, 5, 7, 9], [0, 2, 4, 6, 8]]

In [27]:
# Reshape
print(array.reshape((5,2),order = 'C'))
print('\n',array.reshape((5,2),order = 'F'))

[[1 3]
 [5 7]
 [9 0]
 [2 4]
 [6 8]]

 [[1 4]
 [0 7]
 [3 6]
 [2 9]
 [5 8]]


In [32]:
# Resize
array.resize((3,5), refcheck=False)
array

array([[1, 3, 5, 7, 9],
       [0, 2, 4, 6, 8],
       [0, 0, 0, 0, 0]])

##### <font color = antiquewhite> Statistics

In [33]:
# Mean
array = np.array([1,5,18,20,47,16,12,28,39])
print("Mean:", array.mean())

Mean: 20.666666666666668


In [34]:
# Standard Deviation
print("Standard Deviation:", array.std())

Standard Deviation: 14.220486005134362


In [35]:
# Sum
print("Sum:", array.sum())

Sum: 186


##### <font color = antiquewhite> Selection

In [40]:
print(array)
print(f'First element: {array[0]}\nLast element: {array[-1]}\nFirst 3 elements: {array[:3]}\nLast 3 elements: {array[-3:]}\nEvery two elements{array[::2]}')	

[ 1  5 18 20 47 16 12 28 39]
First element: 1
Last element: 39
First 3 elements: [ 1  5 18]
Last 3 elements: [12 28 39]
Every two elements[ 1 18 47 12 39]


In [44]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
print(f'First line: {array[0]}\nLast line: {array[-1]}\nFirst column: {array[:,0]}\nLast column: {array[:,-1]}\nFirst column, second line: {array[1,0]}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
First line: [1 2 3]
Last line: [7 8 9]
First column: [1 4 7]
Last column: [3 6 9]
First column, second line: 4


##### <font color = antiquewhite> Operations

In [51]:
value = np.array([10.5,20.45,30.7,40.9,100.25])
amount = np.array([20,15,74,10,2])

print(value * amount)
print(value**2 / amount)

[ 210.    306.75 2271.8   409.    200.5 ]
[   5.5125       27.88016667   12.73635135  167.281      5025.03125   ]


##### <font color = antiquewhite> Comparasion between arrays and lists

In [45]:
np_array = np.arange(1000000)
py_list = list(range(1000000))

In [46]:
%time for _ in range(100): np_array *= 2

Wall time: 45 ms


In [47]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

Wall time: 7.51 s
